# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07c0fc889aab854da8da0709fe149e6fd6140f173a22abf9716d09a2fcf3da7ab528487b75f8182cdb17361366dddd885178bb7c79a971d9018c4ef6140a49c1

test:
  secret_key_base: 9f7e8c063cbbb8041898e9ef61922fc1f70f59013e5ae659574d4d92172ff0a6fece19e12e32a7f4b1593af63ff41e9ba46ad67cf0104aa79139d0eb8d2d6616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
